resources:
  - namespace.yaml
  - db-app-namespace.yaml
  - eso-reader-sa.yaml
  - eso-backend-role.yaml
  - eso-backend-rolebinding.yaml
  - operatorgroup.yaml
  - subscription.yaml
  - backend/namespace.yaml
  - backend/postgres-source-secret.yaml
  - clustersecretstore.yaml
  - externalsecret-postgres.yaml

